### PR TITLE
Make stress tester run continuously by reloading itself

### PR DESCRIPTION
**Pull request by eduard-netsajev**

### CODE REVIEW

**Comment by Mukundan314** [comment]
Can't we achieve the same result by making the `tests` argument an infinite iterator?

example:
```python
import random

def test_gen():
    while True:
        yield str(random.random())

tests = test_gen()
solution = cmd2func(['python', 'A.py'])

stress_tester(tests, solution)
```

**Comment by eduard-netsajev** [comment]
That only works if the test generator is a non-fixed random generator that we don't want to change.
The proposed solution allows to change code and see the changes immediately without stopping and stopping the script.

Example: let's say I want modify current generator to return a tuple of (<random value>, <random boolean>) so that end result is something like this:

```python
import random

def test_gen():
    while True:
        yield str(random.random()), bool(random.randint(0, 1))

tests = test_gen()
solution = cmd2func(['python', 'A.py'])

stress_tester(tests, solution)
```

To see these changes in a continuously running stress tester I will have to stop and re-run it again, because the loaded code is still testing on old test generator. With proposed solution the changes are reflected immediately without script interruption.

**Comment by Mukundan314** [comment]
Can't we use something like [nodemon](https://github.com/remy/nodemon) or [watchdog](https://github.com/gorakhargosh/watchdog) for this?

**Comment by cheran-senthil** [comment]
There is no need for any external dependency overall. If you have alternative approaches (without dependencies), feel free to make a PR with your approach.

**Pull request merged**
